print("hello Git")
print("Hello from m-o.")
print("hello again from Iphone")
print("final try")
print("this time it is")
print("please work")
print("I gave up and decided to make the repo public, lel.")
print("Duplicated this line for a quick test.")
print("editing file from termius")
print("gonna test the personal token")
print("boi")
print("hello 2")
